version: '2.1'
services:
  api:
    build: ./graphql-api
    volumes: 
      - npm-cache:/root/.npm
    links: 
      - mysql:mysql
    depends_on:
      - redis
      - mysql
    ports:
      - 5000:5000
      - 9229:9229
    # command:
    #   - node
    #   - "--inspect-brk=0.0.0.0"
    #   - "./build" 
  redis:
    image: 'redis:latest'
    ports:
      - 6397:6397
  mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data-volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    
volumes:
  data-volume:
  npm-cache:
    external: false
